var facts = [];
facts.push('After playing their first two West Coast seasons at Seals Stadium, the Giants moved to Candlestick Park in 1960, which would serve as their home field for four decades. The infamously windy stadium hosted hundreds of important sporting events as well as one particularly noteworthy cultural moment. On August 29, 1966, the Beatles played their last ever (paid) concert together at Candlestick Park. Forty-eight years later, Paul McCartney returned to Candlestick for a send-off performance before the stadium closed this past summer.');
facts.push('The 1989 World Series between the San Francisco Giants and the Oakland As was dominated by one thing and one thing only: The 6.9 magnitude Loma Prieta earthquake that struck the Bay Area just before the start of Game 3 at Candlestick. It lasted for about 15 seconds, starting at 5:04 p.m., with the game scheduled to start at 5:35. Play was suspended for 10 days while the two cities recovered, but the convergence of the World Series and the natural disaster had some interesting results. Because television crews were on hand for the game, Loma Prieta ended up being the first ever earthquake caught on camera. Even more fortuitously, experts think the timing of the earthquake so close to the major game may have saved lives: Most people in the area were inside somewhere to watch the game, and not out on the roads, which were heavily damaged.');
facts.push('Current Giants Manager Bruce Bochy has the largest head in Major League Baseball. He wears a size 8 1/4 hat and, during his playing days, he had to take his batting helmet with him from team to team in the event of a trade. It was easier for his new team to paint the helmet than to find one in his size.');
facts.push('Theres a lot to say about one-time face-of-the-franchise Tim Lincecums career, which has been marked by both extreme highs and confounding lows (especially if hes your favorite player). The record that perhaps best summarizes his many successes is this: He is one of only two players ever with multiple no-hitters thrown, multiple Cy Young Awards won, multiple World Series championship titles and multiple All-Star selections. The other is Sandy Koufax.');
facts.push('In 1994, the MLB season was cut short by labor issues. This impacted every team, player, and fan, of course, but for Giants slugger Matt Williams, it may have cost him a chance at history. When the strike suspended play for the Giants after 115 games, Williams—not Barry Bonds, who hit behind him in the lineup—was on track to top Roger Maris single season home run record. Although it has since been (questionably) surpassed by multiple players, at the time the record for the most home runs in a single season stood at 61. And with 47 games left to play that never came to pass, Williams had hit 43. Even with the shortened season, it was the most Williams ever hit in a single year.');
facts.push('The Giants won the first ever Interleague game, 4-3, against the Indians on June 12, 1997.');
facts.push('The 2003 Giants were just the ninth team in baseball history to wire-to-wire in first place.');
facts.push('Giants fans love Hunter Pence for his scooter, his sense of humor, his ability to motivate his teammates, and, of course, the legion of highly-specific, mild-mannered signs hes inspired. But even the orange and black faithful know Pence does not play baseball gracefully. His wonky style of hitting, throwing and running are immediately evident to anyone who watches him, but it was recently revealed that there is a reason for his jerky motions. Pence has Scheuermanns Disease, a spinal disorder that impairs flexibility. The outfielder himself didnt know about it until undergoing a physical before signing a contract extension with the Giants in 2013.');
facts.push('The spinal stiffness clearly isnt impacting Pences durability: He holds the current active record for consecutive regular season games played with 383.');
facts.push('The teams named changed to the Giants in 1885. Legend has it player-manager Jim Mutrie congratulated his teammates after a particularly convincing victory by calling them "my big fellows, my giants." The name stuck.');
facts.push('Mascot Lou Seal was the first member of the Giants to wear what is now the teams orange Friday jerseys. His was a prototype.');
facts.push('But Lou was not the Giants first mascot. In 1984, the team introduced Crazy Crab, a counter-culture "anti-mascot" that was intentionally hapless and boo-able. The target proved to be just a little too tempting during a 96-loss season in which fans and players alike lobbed not just insults but food, trash, and even resin bags at the crab, forcing him into retirement after just one season.');
facts.push('The Giants have the most Hall of Fame inductees of any organization with 56.');
facts.push('They also have the most wins historically with 10,780. This is helped to be made possible by the fact that they are the sixth-oldest franchise.');
facts.push('The Giants entered the World Series this year having won their last eight-straight playoff series, which is the second-longest streak in baseball history. It wasnt easy the whole way; in 2012, they became the first team in the history of the Division Series to advance after falling into an 0-2 deficit.');
facts.push('Despite his hard-line stance just a year before, McGraw was forced to capitulate to the fans the following season and, after going 105-48 during the regular season, the Giants made their postseason debut in the 1905 World Series, topping the Philadelphia Athletics four games to one. Even in a matchup dominated by otherworldly pitcher performances—it remains the only Series to date in which all five games ended in a shutout—Giants ace Christy Mathewson stood out. Fresh off his second-consecutive 30-win season, the 25-year-old pitched three complete game shutouts over the span of just six days, the only pitcher to have ever done so in a World Series.');
facts.push('The Giants lost to the Yankees in the 51 Fall Classic, but theyd get one more shot at the World Series before leaving New York behind: 1954 was not only their last Championship on the East Coast, it was also the setting of "The Catch"—the amazing defensive play by Willie Mays to preserve a tie in the eighth inning of Game 1 at the Polo Grounds. The Giants would go on to sweep the Cleveland Indians in four games but its the iconic photo of Mays catch that made the Series famous. The photo was one of a series from that play taken by New York Daily News photographer Frank Hurley with his new Hultcher 70 camera, one of the first cameras capable of taking multiple frames per second.');
facts.push('The Giants and the Dodgers both left New York City for California in 1957, leaving the city without a National League team until the Mets were founded in 1962. The Mets chose their colors, blue and orange, to honor each of their NL forefathers in New York.');
facts.push('On July 2, 1963, Giants pitcher Juan Marichal earned the win in The Greatest Game ever pitched. To do so, he bested Braves pitcher Warren Spahns final line of one run on nine hits over 15 1/3 innings with his own 16 full scoreless innings. The two twirlers had traded zeroes all afternoon at Candlestick Park, refusing to yield to the opposing batters or the bullpen. At one point, 25-year-old Marichal is said to have told Giants manager Alvin Dark, "He’s 42 and I’m 25, and you can’t take me out until that man is not pitching."');


//facts: http://mentalfloss.com/article/59622/25-things-you-might-not-know-about-san-francisco-giants


function fact_picker(facts){
  var random_position = Math.floor(Math.random() * (facts.length-1)) + 1;  // returns a number between 1 and target length
  var target_fact = facts[random_position];
  return(target_fact)

}
